TrainingArguments:
  output_dir: artifacts/model_pegasus_samsum
  num_train_epochs: 10
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  logging_dir: ./logs
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 999
  gradient_accumulation_steps: 16