from .stage_1_data_ingestion_pipeline import DataIngestionPipeline
from .stage_2_data_transfomation_pipeline import DataTransformationPipeline
from .stage_3_model_trainer_pipeline import ModelTrainerPipeline
from .stage_4_model_evaluation import ModelEvaluationPipeline
from .prediction_pipeline import PredictionPipeline